services:
  artists-client:
    build: .
    container_name: artists-client
    env_file: .env
    ports:
      - ${APP_PORT-:80}:80
      - ${SECURE_PORT-:443}:443
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/ssl-conf:/etc/nginx/ssl-conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
